import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'slv-001',
    title: 'Echoes of the Void',
    artist: 'Nox Aeterna',
    price: 25,
    category: 'release',
    format: '12" Vinyl',
    releaseDate: '2024-01-15',
    description: 'A haunting journey through ambient soundscapes and industrial textures. Limited edition clear vinyl.',
    imageUrl: 'https://picsum.photos/seed/slv001/800/800',
    catalogNumber: 'SLV001',
    stock: 50,
    tags: ['ambient', 'industrial', 'vinyl'],
  },
  {
    id: 'slv-002',
    title: 'Neon Pulse',
    artist: 'Cyber Drift',
    price: 20,
    category: 'release',
    format: 'CD',
    releaseDate: '2024-02-10',
    description: 'High-energy synthwave for the modern age. Includes digital download code.',
    imageUrl: 'https://picsum.photos/seed/slv002/800/800',
    catalogNumber: 'SLV002',
    stock: 100,
    tags: ['synthwave', 'electronic', 'cd'],
  },
  {
    id: 'slv-003',
    title: 'Rhythmic Chaos',
    artist: 'The Glitch',
    price: 30,
    category: 'release',
    format: '12" Vinyl',
    releaseDate: '2023-11-20',
    description: 'Experimental techno that pushes the boundaries of rhythm. Heavyweight black vinyl.',
    imageUrl: 'https://picsum.photos/seed/slv003/800/800',
    catalogNumber: 'SLV003',
    stock: 25,
    tags: ['techno', 'experimental', 'vinyl'],
  },
  {
    id: 'dst-001',
    title: 'Midnight Sun',
    artist: 'Solaris',
    price: 22,
    category: 'distro',
    format: '12" Vinyl',
    releaseDate: '2024-03-01',
    description: 'Imported from the finest underground labels. Melodic deep house.',
    imageUrl: 'https://picsum.photos/seed/dst001/800/800',
    stock: 15,
    tags: ['house', 'deep house', 'vinyl'],
  },
  {
    id: 'mch-001',
    title: 'Selvajaria Logo Tee',
    artist: 'Selvajaria Records',
    price: 35,
    category: 'merch',
    format: 'Apparel',
    releaseDate: '2023-12-01',
    description: 'High-quality cotton t-shirt with screen-printed logo. Available in all sizes.',
    imageUrl: 'https://picsum.photos/seed/mch001/800/800',
    stock: 200,
    tags: ['apparel', 'logo', 'merch'],
  },
  {
    id: 'mch-002',
    title: 'Label Tote Bag',
    artist: 'Selvajaria Records',
    price: 15,
    category: 'merch',
    format: 'Accessory',
    releaseDate: '2023-12-05',
    description: 'Heavy-duty canvas tote bag for your vinyl hauls.',
    imageUrl: 'https://picsum.photos/seed/mch002/800/800',
    stock: 150,
    tags: ['accessory', 'bag', 'merch'],
  },
];
